export enum DeviceTypes {
  TEMPERATURE_SENSOR = 'TEMPERATURE_SENSOR',
  MOTION_SENSOR = 'MOTION_SENSOR',
  TOUCH_SENSOR = 'TOUCH_SENSOR',
  ROSETTE = 'ROSETTE',
  LIGHT = 'LIGHT',
  QR_SCANNER = 'QR_SCANNER',
}
